-- Phase 5: server-wide AI provider choice, the per-user run lock and the run log.
-- The API keys are NOT here: they live in `.env` (GEMINI_API_KEY, JEV_API_KEY),
-- per the project's config split — secrets via env, admin-tunable values in
-- app_settings. A null provider means the AI is off for the whole instance.
-- Which providers exist is the code's business (the jobs crate's registry), so
-- adding one never needs a migration.

alter table app_settings
    add column budget_ai_provider text,
    add column budget_ai_model    text;

-- One row while a categorisation run holds a user. Claimed with an insert that
-- only takes over a row whose heartbeat is stale; the run beats once per batch.
-- Swept at boot too, because the app is single-process and any row found then
-- belongs to a dead run.
create table budget_ai_lock (
    user_id      uuid primary key references users (id) on delete cascade,
    heartbeat_at timestamptz not null default now()
);

-- One row per run, inserted when the run starts and updated after every paid
-- call, so the spend survives a run that dies half-way. `running` is only ever
-- seen on a live run or on one that died; the next run for the user, and the
-- boot sweep, close those as `error`.
create table budget_ai_run (
    id             uuid primary key default gen_random_uuid(),
    user_id        uuid not null references users (id) on delete cascade,
    started_at     timestamptz not null default now(),
    model          text not null,
    tokens_in      bigint not null default 0,
    tokens_out     bigint not null default 0,
    -- False once any call of the run did not report its token counts: the
    -- totals are then a floor, not the bill.
    usage_complete boolean not null default true,
    outcome        text not null default 'running'
                   check (outcome in ('running', 'ok', 'partial', 'error')),
    error          text
);

create index budget_ai_run_user_idx on budget_ai_run (user_id, started_at desc);

-- The normalised description, stored so the AI's evidence lookup can use an
-- index for both the exact match and the trigram neighbours instead of
-- re-normalising every confirmed row once per item. Regenerated by Postgres on
-- every write of `description`; if `budget_norm_description` ever changes, the
-- column has to be rebuilt with it.
alter table transaction
    add column description_norm text
        generated always as (budget_norm_description(description)) stored;

create index transaction_description_norm_idx on transaction (description_norm);
create index transaction_description_norm_trgm_idx
    on transaction using gin (description_norm gin_trgm_ops);
