[package]
name = "gripsou-jobs"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
gripsou-core = { path = "../core" }
gripsou-providers = { path = "../providers" }
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
sqlx.workspace = true
anyhow.workspace = true
chrono.workspace = true
hmac = "0.12"
sha2 = "0.10"
base64 = "0.22"
