[package]
name = "gripsou-providers"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
gripsou-core = { path = "../core" }
async-trait.workspace = true
serde = { workspace = true }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
rust_decimal = { workspace = true }
reqwest = { workspace = true }
urlencoding = { workspace = true }
chrono = { workspace = true }
tracing.workspace = true
yahoo_finance_api = "4.1"
time = "0.3"
hmac = "0.12"
sha2 = "0.10"
base64 = "0.22"

[dev-dependencies]
tokio = { workspace = true }
wiremock = "0.6"
